Project: Weather App
LamiaSristy/Weather-App-JS pull request #1
Opened 2020-12-24 15:17 UTC by LamiaSristy

This project is an app that will take a location and then hit the API to get all the weather information and display it.

Here I have practiced:

- Working with APIs
-  JSON
-  Async and Await 
-  JavaScript DOM manipulation.

2020-12-24 16:10 UTC, Forison requested changes
## Status::Changes required❌
# 🙋‍♂️ @LamiaSristy 
#### You have done a great job on this one so far, Your code is very clean and your UI was awesome, however, there are a few issues we have to address to get this project approved🤗.
* [ ] It has a toggle control to determine if the result will be shown in Celsius or Fahrenheit. Currently, it displays in both units, let adjust it to display in one unit ie degree, and then display in Fahrenheit when clicked.
* [ ] It changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
Let us make users experience different appearances based on the temperature, maybe the color of opacity could be tweak to change in color based on the temperature range, etc...
* [ ] Let us remove all `console.log()` you risk exposing vital information of your application in production make sure you get rid of them after development.
**[OPTIONAL]**
* [ ] Add `"start": "webpack-dev-server --mode development --open"` your script file to enable application to be launch with the `npm start` command.
* [ ] it has a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
* [ ] it fetches the current geolocation of the user when the app is first accessed and fetches the weather from that location
#### That is it, kindly make the change and submit a re-review🤗.
#### Happy coding😎
Addo Forison

2020-12-24 16:10 UTC, Forison commented on src/index.js
> +    console.log('WeatherData');
remove all `console.log` from code

2020-12-25 01:43 UTC, LamiaSristy commented on src/index.js
> +    console.log('WeatherData');
Done.

2020-12-25 05:14 UTC, shloch approved these changes
## Hello @LamiaSristy 

Great job bringing all the corrections proposed by former TSE. It's all smooth now and working great
![weather](https://user-images.githubusercontent.com/40712459/103120522-65a0f800-4678-11eb-94fa-49537eb83ab8.gif)

You can merge this.
Happy coding

2020-12-26 19:56 UTC, merged